### ISSUE TITLE
Service Code

### ISSUE THREAD

**Issue by veekram** [Jyaasa/esewa#4]
@gkunwar I had gone thorough some of your codes. Pretty well (y). I was really hoping to add some remaining tasks as transaction and some *TODO* .

**Comment by veekram** [comment]
My bad, I already has unusable esewa test account.

**Comment by gkunwar** [comment]
@veekram Thanks for your interest to contribute some valuable code to this gem. Unfortunately  eSewa test account no longer working. You can get new test account from eSewa. Please contact with esewa for new test account.
Thanks.

**Comment by veekram** [comment]
@gkunwar I hope to look forward on this gem soon :)
